
  /* ─────────────────────────────────────
   * INFANTIL (nuevo)
   * ───────────────────────────────────── */
  {
    codigo:      "INF-01",
    titulo:      "¡Buenos días tractorcito!",
    autor:       "Novelty Ediciones",
    categoria:   "INF",
    estado:      "B",
    paginas:     15,
    year:        2020,
    editorial:   "Novelty Ediciones",
    isbn:        "",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "Un libro de cartón lleno de colores y texturas para los más pequeños. El tractorcito saluda cada mañana con energía y entusiasmo. Ideal para despertar el amor por los libros desde muy temprana edad."
  },
  {
    codigo:      "INF-02",
    titulo:      "Oso y Ratona ¡Buenos días!",
    autor:       "Nicola Edwards",
    categoria:   "INF",
    estado:      "B",
    paginas:     16,
    year:        2021,
    editorial:   "Beascoa",
    isbn:        "",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "Oso y Ratona se despiertan cada mañana con una gran sonrisa. Un libro de páginas resistentes para los más pequeños, lleno de ilustraciones alegres y palabras sencillas para aprender a saludar el día."
  },

  /* ─────────────────────────────────────
   * CLÁSICOS — versiones abreviadas y nuevos
   * ───────────────────────────────────── */
  {
    codigo:      "CLA-04",
    titulo:      "Moby Dick (versión abreviada)",
    autor:       "Herman Melville",
    categoria:   "CLA",
    estado:      "A",
    paginas:     96,
    year:        2019,
    editorial:   "Silver Dolphin",
    isbn:        "9786075323718",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "La legendaria historia del capitán Ahab y su obsesión por cazar a la ballena blanca más temida de los mares. Esta versión abreviada conserva toda la emoción de la novela original en un formato accesible para jóvenes lectores."
  },
  {
    codigo:      "CLA-05",
    titulo:      "Don Quijote de la Mancha (versión abreviada)",
    autor:       "Miguel de Cervantes",
    categoria:   "CLA",
    estado:      "A",
    paginas:     94,
    year:        2019,
    editorial:   "Silver Dolphin",
    isbn:        "",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "El caballero andante más famoso de la literatura española en una versión adaptada para jóvenes. Las aventuras de Don Quijote y Sancho Panza cobran vida con ilustraciones y un lenguaje cercano sin perder la esencia de la obra original."
  },
  {
    codigo:      "CLA-06",
    titulo:      "Romeo y Julieta",
    autor:       "William Shakespeare",
    categoria:   "CLA",
    estado:      "A",
    paginas:     94,
    year:        2019,
    editorial:   "Silver Dolphin",
    isbn:        "9786075323718",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "La historia de amor más famosa de todos los tiempos, adaptada para jóvenes lectores. Dos jóvenes de familias enemigas se enamoran en la Verona del siglo XVI. Una versión accesible de la obra maestra de Shakespeare."
  },

  /* ─────────────────────────────────────
   * NARRATIVA — nuevos títulos guatemaltecos
   * ───────────────────────────────────── */
  {
    codigo:      "NAR-08",
    titulo:      "Lunas y noches",
    autor:       "Manuel Bolom Yaxcal",
    categoria:   "NAR",
    estado:      "A",
    paginas:     30,
    year:        2015,
    editorial:   "Diario de Centro América y Tipografía Nacional",
    isbn:        "9789929560543",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "Una colección de poemas que recorre el ciclo de la noche y la luna desde la sensibilidad de la cosmovisión maya. Bolom Yaxcal construye imágenes poéticas que mezclan la naturaleza, el tiempo y la memoria de un pueblo con voz propia."
  },
  {
    codigo:      "NAR-09",
    titulo:      "La manzana de la discordia",
    autor:       "Enrique Noriega",
    categoria:   "NAR",
    estado:      "A",
    paginas:     0,
    year:        "",
    editorial:   "Tipografía Nacional",
    isbn:        "",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "Una obra narrativa de uno de los escritores guatemaltecos más prolíficos. Noriega teje una historia donde el conflicto y la discordia sirven de motor para explorar las relaciones humanas y las tensiones que definen a una sociedad."
  },
  {
    codigo:      "NAR-10",
    titulo:      "Fábulas",
    autor:       "Rafael García Goyena",
    categoria:   "NAR",
    estado:      "A",
    paginas:     204,
    year:        "",
    editorial:   "Tipografía Nacional",
    isbn:        "9789929560697",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "Las fábulas de García Goyena son una joya de la literatura guatemalteca del siglo XIX. Con animales como protagonistas, cada historia encierra una moraleja ingeniosa sobre la condición humana, la astucia y la justicia."
  },
  {
    codigo:      "NAR-11",
    titulo:      "La niña de Guatemala",
    autor:       "Máximo Soto Hall",
    categoria:   "NAR",
    estado:      "A",
    paginas:     0,
    year:        "",
    editorial:   "Tipografía Nacional",
    isbn:        "9789929560703",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "Una novela corta que inmortalizó a María García Granados, la joven que inspiró los versos más famosos de José Martí. Una historia de amor no correspondido narrada con delicadeza y anclada en la historia de Guatemala del siglo XIX."
  },
  {
    codigo:      "NAR-12",
    titulo:      "Concierto floral en primavera: Poemas",
    autor:       "Álvaro Enrique Palma Sandoval",
    categoria:   "NAR",
    estado:      "A",
    paginas:     0,
    year:        1993,
    editorial:   "",
    isbn:        "",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "Una colección de poemas que celebra la primavera con imágenes florales y musicalidad. Palma Sandoval construye versos llenos de color y vida, donde la naturaleza se convierte en metáfora de los sentimientos más profundos."
  },
  {
    codigo:      "NAR-13",
    titulo:      "Antes del relámpago — Tomo I",
    autor:       "Enrique Noriega",
    categoria:   "NAR",
    estado:      "A",
    paginas:     0,
    year:        "",
    editorial:   "Editorial Cultura",
    isbn:        "",
    copias:      1,
    disponible:  false,
    nota:        "⚠ Ejemplar donado — consultar disponibilidad.",
    descripcion: "Primer tomo de la obra narrativa más ambiciosa de Enrique Noriega. Una exploración profunda de la historia y la identidad guatemalteca a través de personajes que viven en la antesala de grandes cambios sociales y políticos."
  },
  {
    codigo:      "NAR-14",
    titulo:      "Antes del relámpago — Tomo II",
    autor:       "Enrique Noriega",
    categoria:   "NAR",
    estado:      "A",
    paginas:     0,
    year:        "",
    editorial:   "Editorial Cultura",
    isbn:        "",
    copias:      1,
    disponible:  false,
    nota:        "⚠ Ejemplar donado — consultar disponibilidad.",
    descripcion: "Segundo tomo de esta obra fundamental. La historia continúa explorando las tensiones sociales, políticas y humanas de Guatemala, con la misma intensidad narrativa que caracteriza la escritura de Noriega."
  },
  {
    codigo:      "NAR-15",
    titulo:      "El Quetzal, Colibrí Gigante",
    autor:       "Enrique Noriega",
    categoria:   "NAR",
    estado:      "A",
    paginas:     432,
    year:        "",
    editorial:   "Editorial Cultura",
    isbn:        "9789993943440",
    copias:      1,
    disponible:  false,
    nota:        "⚠ Ejemplar donado — consultar disponibilidad.",
    descripcion: "Una obra monumental sobre el ave nacional de Guatemala. Noriega combina investigación, historia y narrativa para trazar el recorrido simbólico del quetzal a través de la cultura, la mitología y la identidad del pueblo guatemalteco."
  },
  {
    codigo:      "NAR-16",
    titulo:      "Coplas de amor y delirio del alma",
    autor:       "Plinio Eduardo Cortés",
    categoria:   "NAR",
    estado:      "A",
    paginas:     0,
    year:        "",
    editorial:   "",
    isbn:        "",
    copias:      1,
    disponible:  false,
    nota:        "⚠ Ejemplar donado — consultar disponibilidad.",
    descripcion: "Una colección de coplas donde el amor y el delirio se entrelazan en versos de musicalidad popular. Cortés recupera la tradición de la copla para hablar del alma humana con humor, ternura y una hondura inesperada."
  },
  {
    codigo:      "NAR-17",
    titulo:      "El principito",
    autor:       "Antoine de Saint-Exupéry",
    categoria:   "NAR",
    estado:      "A",
    paginas:     0,
    year:        "",
    editorial:   "Piedra Santa",
    isbn:        "",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "Un pequeño príncipe que viaja de planeta en planeta aprende que lo esencial es invisible a los ojos. El libro más leído del mundo después de la Biblia es, a la vez, un cuento para niños y una reflexión para adultos sobre la amistad, el amor y el sentido de la vida."
  },

  /* ─────────────────────────────────────
   * CÍVICA / HISTORIA (nueva categoría CIV)
   * ───────────────────────────────────── */
  {
    codigo:      "CIV-01",
    titulo:      "Constitución Política de la República de Guatemala",
    autor:       "",
    categoria:   "CIV",
    estado:      "A",
    paginas:     0,
    year:        "",
    editorial:   "Diario de Centro América y Tipografía Nacional",
    isbn:        "",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "El documento fundamental que rige la vida jurídica y política de Guatemala. Establece los derechos y deberes de los ciudadanos, la organización del Estado y los principios que garantizan la dignidad de todas las personas. Lectura indispensable para todo ciudadano."
  },
  {
    codigo:      "CIV-02",
    titulo:      "Barrios: Heroísmo y conciencia de la guatemalidad",
    autor:       "Amílcar Echeverría",
    categoria:   "CIV",
    estado:      "A",
    paginas:     0,
    year:        "",
    editorial:   "Tipografía Nacional",
    isbn:        "",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "Un recorrido por la figura del General Justo Rufino Barrios y su papel en la construcción de la identidad guatemalteca. Echeverría analiza con rigor histórico el legado de uno de los personajes más influyentes y controvertidos de la historia nacional."
  },
  {
    codigo:      "CIV-03",
    titulo:      "Independencia de Centroamérica",
    autor:       "",
    categoria:   "CIV",
    estado:      "A",
    paginas:     0,
    year:        "",
    editorial:   "",
    isbn:        "",
    copias:      1,
    disponible:  true,
    nota:        "",
    descripcion: "Un documento histórico sobre el proceso de independencia de las provincias de Centroamérica del dominio español en 1821. Recorre los antecedentes, los protagonistas y las circunstancias que llevaron a uno de los momentos más importantes de la historia regional."
  },

